# Docker Compose for OMS Chat Bot Development
version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: oms_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: company_kb
    volumes:
      - mongodb_data:/data/db

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: oms_qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  # ArangoDB Graph Database  
  arangodb:
    image: arangodb:3.11
    container_name: oms_arangodb
    restart: always
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: your_arango_password
    volumes:
      - arangodb_data:/var/lib/arangodb3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: oms_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  qdrant_data:
  arangodb_data:
  redis_data:

networks:
  default:
    name: oms_network